### ISSUE TITLE
Skip validation only when the value is null or empty string

### ISSUE THREAD

**Issue by morawskim** [Happyr/entity-exists-validation-constraint#5]
Hello,

PR #4 was added a condition to skip the validation if the value is empty. Sometimes we can use an entity with id equals to 0 eg. for anonymous user. The mentioned Symfony validator NotBlank allows for value 0 (https://symfony.com/doc/current/reference/constraints/NotBlank.html). Maybe we should skip validation only if the value is null? Many Symfony validators have a condition `null === $value || '' === $value` for skip validation.
What do you think?

If you agree I can create PR.

**Comment by Nyholm** [comment]
Sorry for the super late reply. You are 100% correct. 

I fixed this in #8, I'll soon make a new release
